#!/usr/bin/env bash

###############################################################################
# Local Services Booking Platform - Setup & Configuration Guide
# 
# This document provides comprehensive configuration instructions for
# running the complete application stack
###############################################################################

echo "════════════════════════════════════════════════════════════════════"
echo "  LOCAL SERVICES BOOKING PLATFORM - CONFIGURATION GUIDE"
echo "════════════════════════════════════════════════════════════════════"
echo ""

###############################################################################
# SECTION 1: CURRENT STATUS
###############################################################################

echo "✅ CURRENT STATUS"
echo "─────────────────────────────────────────────────────────────────────"
echo "Frontend (Next.js):    http://localhost:3000      ✅ RUNNING"
echo "Backend (NestJS):      http://localhost:3001      ✅ RUNNING"  
echo "Health Check:          http://localhost:3001/api/health"
echo "Database:              Optional (PostgreSQL)      ⚠️  NOT REQUIRED"
echo ""
echo "✨ Everything is working! No configuration needed to start coding."
echo ""

###############################################################################
# SECTION 2: QUICK START
###############################################################################

echo "🚀 QUICK START OPTIONS"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "OPTION 1: One-Click Start (Windows)"
echo "  Double-click: start-dev.bat"
echo "  → Opens backend and frontend in separate windows"
echo ""
echo "OPTION 2: Manual Start (Linux/Mac/Windows)"
echo "  Terminal 1:"
echo "    cd backend"
echo "    npm run start"
echo ""
echo "  Terminal 2:"
echo "    cd local-services-ui"
echo "    npm run dev"
echo ""
echo "OPTION 3: Check Service Status"
echo "  node check-health.js"
echo ""

###############################################################################
# SECTION 3: CONFIGURATION FILES
###############################################################################

echo "📝 CONFIGURATION FILES"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "BACKEND CONFIGURATION"
echo "File: backend/.env"
echo "────────────────────"
cat << 'EOF'
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/local_services_db"
NODE_ENV="development"
PORT=3001
EOF
echo ""
echo "Current Settings:"
echo "  • DATABASE_URL: PostgreSQL (optional)"
echo "  • NODE_ENV: development (enables hot reload)"
echo "  • PORT: 3001 (backend server)"
echo ""
echo "To Change:"
echo "  1. Edit backend/.env"
echo "  2. Run: cd backend && npx prisma generate && npm run build"
echo "  3. Restart: npm run start"
echo ""
echo "FRONTEND CONFIGURATION"
echo "File: local-services-ui/.env.local (optional)"
echo "────────────────────────────────────────────"
echo "NEXT_PUBLIC_API_URL=http://localhost:3001/api"
echo ""
echo "Note: Frontend works without this file"
echo "      Default API URL is http://localhost:3001/api"
echo ""

###############################################################################
# SECTION 4: DATABASE SETUP (OPTIONAL)
###############################################################################

echo "💾 DATABASE SETUP (OPTIONAL)"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "For hackathon demo: Database is NOT required"
echo ""
echo "If you want PostgreSQL:"
echo ""
echo "STEP 1: Install PostgreSQL"
echo "  • Download: https://www.postgresql.org/download/"
echo "  • During install:"
echo "    - Set port: 5432 (default)"
echo "    - Set password for 'postgres' user"
echo ""
echo "STEP 2: Create Database"
echo "  psql -U postgres"
echo "  CREATE DATABASE local_services_db;"
echo "  \\q"
echo ""
echo "STEP 3: Update .env"
echo "  Edit backend/.env"
echo "  DATABASE_URL=\"postgresql://postgres:YOUR_PASSWORD@localhost:5432/local_services_db\""
echo ""
echo "STEP 4: Run Migrations"
echo "  cd backend"
echo "  npx prisma migrate dev --name init"
echo ""
echo "STEP 5: Verify Connection"
echo "  npm run start"
echo "  Check logs: should see '✅ Database connected successfully'"
echo ""
echo "NOTE: Without PostgreSQL:"
echo "  • Backend still runs"
echo "  • API endpoints work"
echo "  • Logs show database error (ignore it)"
echo "  • Use mock data for demo"
echo ""

###############################################################################
# SECTION 5: ENVIRONMENT VARIABLES EXPLAINED
###############################################################################

echo "⚙️  ENVIRONMENT VARIABLES EXPLAINED"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "DATABASE_URL"
echo "  Purpose: PostgreSQL connection string"
echo "  Format:  postgresql://user:password@host:port/dbname"
echo "  Default: postgresql://postgres:postgres@localhost:5432/local_services_db"
echo "  Change:  Edit backend/.env, rebuild, restart"
echo ""
echo "NODE_ENV"
echo "  Purpose: Application environment"
echo "  Options: development | production | test"
echo "  Default: development (enables hot reload)"
echo "  Use:     Set to 'production' for deployment"
echo ""
echo "PORT"
echo "  Purpose: Backend server port"
echo "  Default: 3001"
echo "  Change:  If port is busy, set to 3002, 3003, etc."
echo ""
echo "NEXT_PUBLIC_API_URL (Frontend)"
echo "  Purpose: Backend API URL for frontend"
echo "  Default: http://localhost:3001/api"
echo "  Change:  Only if running on different port/host"
echo ""

###############################################################################
# SECTION 6: API ENDPOINTS
###############################################################################

echo "🔗 API ENDPOINTS (Backend)"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "Implemented:"
echo "  GET  /              → API info"
echo "  GET  /api/health    → Service status"
echo ""
echo "Ready for Implementation:"
echo "  POST   /api/auth/login"
echo "  POST   /api/auth/verify-otp"
echo "  GET    /api/users/:id"
echo "  PUT    /api/users/:id"
echo "  GET    /api/workers"
echo "  GET    /api/workers/:id"
echo "  GET    /api/bookings"
echo "  POST   /api/bookings"
echo "  GET    /api/bookings/:id"
echo "  PUT    /api/bookings/:id"
echo "  DELETE /api/bookings/:id"
echo ""

###############################################################################
# SECTION 7: FRONTEND PAGES
###############################################################################

echo "🎨 FRONTEND PAGES"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "Home Page"
echo "  URL:     http://localhost:3000/"
echo "  Status:  ✅ Live"
echo "  Content: Hero, services, featured workers, CTA"
echo ""
echo "Search Page"
echo "  URL:     http://localhost:3000/search?service=plumber"
echo "  Status:  ✅ Live"
echo "  Content: Filter by service, sort by rating/price/distance"
echo ""
echo "Worker Profile"
echo "  URL:     http://localhost:3000/worker/1"
echo "  Status:  ✅ Live"
echo "  Content: Full details, rating, languages, experience"
echo ""
echo "Booking Page"
echo "  URL:     http://localhost:3000/booking"
echo "  Status:  ✅ Live"
echo "  Content: Date picker, time slots, price breakdown"
echo ""
echo "Login Page"
echo "  URL:     http://localhost:3000/login"
echo "  Status:  ✅ Live"
echo "  Content: OTP verification flow"
echo ""
echo "Languages Supported:"
echo "  🇬🇧 English (default)"
echo "  🇮🇳 हिंदी (Hindi)"
echo "  🇮🇳 मराठी (Marathi)"
echo "  Select from navbar"
echo ""

###############################################################################
# SECTION 8: PROJECT STRUCTURE
###############################################################################

echo "📁 PROJECT STRUCTURE"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "backend/"
echo "  ├── src/"
echo "  │   ├── main.ts              (Entry point, validation setup)"
echo "  │   ├── app.module.ts        (Root module)"
echo "  │   ├── app.controller.ts    (Root endpoint)"
echo "  │   ├── prisma/              (Database service)"
echo "  │   ├── modules/             (Feature modules)"
echo "  │   │   ├── auth/            (Login, OTP, JWT)"
echo "  │   │   ├── users/           (User profiles)"
echo "  │   │   ├── workers/         (Worker listings)"
echo "  │   │   ├── bookings/        (Booking management)"
echo "  │   │   └── admin/           (Admin features)"
echo "  │   ├── health/              (Health check)"
echo "  │   ├── common/              (Shared utilities)"
echo "  │   │   ├── decorators/"
echo "  │   │   ├── guards/"
echo "  │   │   ├── filters/"
echo "  │   │   └── interceptors/"
echo "  │   └── config/              (Configuration)"
echo "  ├── prisma/"
echo "  │   └── schema.prisma        (Database models)"
echo "  ├── .env                     (Configuration)"
echo "  └── package.json"
echo ""
echo "local-services-ui/"
echo "  ├── src/"
echo "  │   ├── app/                 (Pages)"
echo "  │   │   ├── page.tsx         (Home)"
echo "  │   │   ├── login/           (Login)"
echo "  │   │   ├── search/          (Search)"
echo "  │   │   ├── worker/[id]/     (Profile)"
echo "  │   │   ├── booking/         (Booking)"
echo "  │   │   └── layout.tsx       (Layout)"
echo "  │   ├── components/          (UI Components)"
echo "  │   │   ├── Navbar.tsx"
echo "  │   │   ├── Footer.tsx"
echo "  │   │   ├── ServiceCard.tsx"
echo "  │   │   ├── WorkerCard.tsx"
echo "  │   │   └── Toast.tsx"
echo "  │   ├── context/             (State management)"
echo "  │   │   └── LanguageContext.tsx"
echo "  │   ├── data/                (Mock data)"
echo "  │   │   ├── services.ts"
echo "  │   │   └── workers.ts"
echo "  │   └── app/globals.css      (Styling)"
echo "  └── package.json"
echo ""

###############################################################################
# SECTION 9: TROUBLESHOOTING
###############################################################################

echo "🆘 TROUBLESHOOTING"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "PROBLEM: Port already in use"
echo "SOLUTION:"
echo "  Option 1: Change PORT in backend/.env to 3002, 3003, etc."
echo "  Option 2: Kill process using port 3000/3001"
echo "  Option 3: Change port in package.json for frontend"
echo ""
echo "PROBLEM: Database connection failed"
echo "SOLUTION:"
echo "  Option 1: Install PostgreSQL (optional)"
echo "  Option 2: Ignore error (database is optional for demo)"
echo ""
echo "PROBLEM: Prisma errors"
echo "SOLUTION:"
echo "  cd backend"
echo "  npx prisma generate"
echo "  npm run build"
echo "  npm run start"
echo ""
echo "PROBLEM: Frontend won't load"
echo "SOLUTION:"
echo "  Delete .next and .turbopack folders"
echo "  rm -r local-services-ui/.next local-services-ui/.turbopack"
echo "  npm run dev"
echo ""
echo "PROBLEM: Changes not showing"
echo "SOLUTION:"
echo "  Restart dev server (Ctrl+C)"
echo "  Clear browser cache"
echo "  npm run dev"
echo ""
echo "PROBLEM: Module not found"
echo "SOLUTION:"
echo "  npm install"
echo ""

###############################################################################
# SECTION 10: TECH STACK
###############################################################################

echo "🛠️  TECH STACK"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "Frontend:"
echo "  • Next.js 16.1.4 (App Router, Turbopack)"
echo "  • TypeScript"
echo "  • Tailwind CSS"
echo "  • Lucide React Icons"
echo "  • React Context API"
echo ""
echo "Backend:"
echo "  • NestJS (Enterprise Node.js)"
echo "  • TypeScript"
echo "  • Prisma ORM"
echo "  • PostgreSQL (optional)"
echo "  • Class Validator"
echo "  • dotenv"
echo ""
echo "Tools:"
echo "  • npm (package manager)"
echo "  • Git (version control)"
echo "  • VS Code (recommended)"
echo ""

###############################################################################
# SECTION 11: NEXT STEPS
###############################################################################

echo "📚 NEXT STEPS"
echo "─────────────────────────────────────────────────────────────────────"
echo ""
echo "1. Start Services"
echo "   Windows: Double-click start-dev.bat"
echo "   Others:  npm run start (backend) & npm run dev (frontend)"
echo ""
echo "2. Open Browser"
echo "   http://localhost:3000"
echo ""
echo "3. Implement API Endpoints"
echo "   backend/src/modules/*"
echo ""
echo "4. Connect Frontend to API"
echo "   Replace mock data with fetch calls"
echo ""
echo "5. Setup Database (Optional)"
echo "   Install PostgreSQL, run migrations"
echo ""
echo "6. Deploy"
echo "   Vercel (frontend), Railway/Render (backend)"
echo ""

###############################################################################
# FOOTER
###############################################################################

echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "  ✨ READY TO START DEVELOPMENT!"
echo ""
echo "  Frontend: http://localhost:3000"
echo "  Backend:  http://localhost:3001"
echo "  Health:   http://localhost:3001/api/health"
echo ""
echo "  For more help, see:"
echo "    • CONFIGURATION.md - Detailed setup"
echo "    • QUICK_SETUP.md - Quick reference"
echo "    • README.md - Project overview"
echo "════════════════════════════════════════════════════════════════════"
echo ""
